# USB Device
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

# Serial / UART
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_UART_BRIDGE=y

# Display
CONFIG_DISPLAY=y
CONFIG_ILI9XXX=y

# LVGL
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_USE_LABEL=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_10=y
CONFIG_LV_USE_FLEX=y
CONFIG_LV_Z_VDB_SIZE=10

# Logging
CONFIG_LOG=y

# Main stack
CONFIG_MAIN_STACK_SIZE=4096

# Heap for LVGL
CONFIG_HEAP_MEM_POOL_SIZE=8192
